version: "3"
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: BlogDB
      MYSQL_USER: user
      MYSQL_PASSWORD: super-secret
      MYSQL_ROOT_PASSWORD: super-secret
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: super-secret
      MYSQL_ROOT_PASSWORD: super-secret
    networks:
      - default
volumes:
  persistent:
